//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class oeg_lookupsEntities : DbContext
    {
        public oeg_lookupsEntities()
            : base("name=oeg_lookupsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetEmployees_Result> GetEmployees(string employeeNumbers)
        {
            var employeeNumbersParameter = employeeNumbers != null ?
                new ObjectParameter("EmployeeNumbers", employeeNumbers) :
                new ObjectParameter("EmployeeNumbers", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployees_Result>("GetEmployees", employeeNumbersParameter);
        }
    
        public virtual ObjectResult<GetPrograms_Result> GetPrograms(string jobCodes)
        {
            var jobCodesParameter = jobCodes != null ?
                new ObjectParameter("JobCodes", jobCodes) :
                new ObjectParameter("JobCodes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrograms_Result>("GetPrograms", jobCodesParameter);
        }
    }
}
