//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        public int ReportDataID { get; set; }
        public string JobCode { get; set; }
        public string Group { get; set; }
        public string ID { get; set; }
        public string QuestionID { get; set; }
        public int PrePost { get; set; }
        public int Score { get; set; }
        public string QualResponse { get; set; }
        public string PQA1 { get; set; }
        public string PQA2 { get; set; }
        public string PQA3 { get; set; }
        public string Factor { get; set; }
        public string School { get; set; }
        public Nullable<int> YearLevel { get; set; }
        public Nullable<int> Days { get; set; }
        public string Venue { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> ProgramStartDate { get; set; }
    }
}
