//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffReportData
    {
        public int StaffReportDataID { get; set; }
        public string ResponseID { get; set; }
        public string JobCode { get; set; }
        public string Group { get; set; }
        public string EmployeeNumber { get; set; }
        public string QuestionID { get; set; }
        public Nullable<int> Score { get; set; }
        public string QualResponse { get; set; }
    }
}
