//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        public int SurveyID { get; set; }
        public string SurveyName { get; set; }
        public string SurveyCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string SurveyType { get; set; }
    }
}
