//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProgram
    {
        public string JobCode { get; set; }
        public string SchoolCode { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> JobFrom { get; set; }
        public Nullable<int> Duration { get; set; }
        public string YearLvl { get; set; }
        public string Year { get; set; }
    }
}
